export interface Auth {
    _id: string;
    createdAt: string;
    email: string;
    name: string;
    password: string;
    role: string;
    status: boolean;
    updatedAt: string;
}

export interface Rol {
    rol: string;
}

// export interface Auth extends User {
//     _id: string;
//     createdAt: string;
//     updatedAt: string;
// }

// Generated by https://quicktype.io

export interface Message {
    ok: boolean;
    user: User;
}

export interface User {
    name: string;
    email: string;
    role: string;
    status: boolean;
    _id: string;
    createdAt: string;
    updatedAt: string;
}
