// Generated by https://quicktype.io

import { Schema } from 'mongoose';

export interface GetKeys {
    keys: Key[];
}

export interface Key {
    _id:         string;
    name:        string;
    description: string;
    user:        Schema.Types.ObjectId;
    createdAt:   string;
    updatedAt:   string;
    image:      string;
}
